spring.datasource.url: jdbc:h2:file:./camunda-h2-database

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

camunda.bpm.admin-user:
  id: demo
  password: demo

camunda:
  bpm:
    authorization:
      enabled: true